### ISSUE TITLE
GPU Support 

### ISSUE THREAD

**Issue by spcqike** [axllent/wireguard-vanity-keygen#1]
Hi 

I want to ask if you think it’s possible to add GPU support. Like hashcat does. I guess this would speed things up and could allow longer personnel strings than 5 or 6. 

Best regards

**Comment by axllent** [comment]
Hi there. I like the idea, but I really don't think this is possible. If it was I believe it would require support within the x/crypto library (which this uses to generate the random hashes), reliance on c-wrappers, and a lot more knowledge of using GPU's to perform those calculations. So whilst I'd gladly accept patches of a working & reliable implementation of this, I won't be able to create it, sorry.
