### ISSUE TITLE
Add timeout option?

### ISSUE THREAD

**Issue by rasa** [axllent/wireguard-vanity-keygen#15]
Users may want the program to quit after a certain amount of time, so perhaps we add a timeout option:
```
  -d, --duration time    exit after time limit has been reached
```
Where `time` is a positive integer, with an optional suffix:

1. `s` for seconds
2. `m` for minutes
3. `h` for hours
4. `d` for days
5. `w` for weeks
6. `M` for months
7. `y` for years

If no suffix is provided, seconds is assumed.

A zero, or a negative value, would be considered an error.

If you find this useful, I will craft a PR for your review.

**Comment by axllent** [comment]
That sounds like another useful feature, though I'd be cautious about calling it "duration" as that may be seen as "go for this long" whereas we mean "timeout" /  "quit after if not complete". Maybe `--timeout` without a short flag (as `-t` is already taken), or alternatively `--quit-after`/`-q`.

Do you think seconds is a useful metric here? Seems way too short for something like this, just as years is too long. Just my initial thoughts...

Happy for you to work on this if you like, thanks!

While talking about improvements (and if you're looking at things to work on), I think the most useful improvement would be speed. I'm not saying it can be improved, but I have yet to profile the app to see if there are any bottlenecks which can be avoided. Some Go tests and benchmarks would be handy too.

Anyway, only if you're keen to work on things, no stress or pressure.

**Comment by rasa** [comment]
@axllent Re speed improvements, [this](https://github.com/warner/wireguard-vanity-address/pull/15/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R22) comment describes a patch the author [says](https://github.com/warner/wireguard-vanity-address/pull/15#issue-575151969) gives a "5x speedup". But this work seems a bit above my pay grade, if I'm to be honest.

If I had more time, I would love to create some tests and benchmarks. I haven't played with Copilot. I wonder if it would write them for us?

**Comment by AlexanderYastrebov** [comment]
> Re speed improvements, this comment describes a patch the author says gives a "5x speedup". But this work seems a bit above my pay grade, if I'm to be honest.

Hello, I've created a similar tool in Go https://github.com/AlexanderYastrebov/wireguard-vanity-key based on ideas from there
